POST  http://localhost:3000/blog
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NjY5NDM2NTcsInV1aWQiOjkzNjIsInVzZXJuYW1lIjoiQzIwMjExMDE1ODg4OCJ9.ax0L91BP0vXMzWISu8tntIiXUr5ts1b_1Tk_YZJmuYt9ikQ9gl8TCwwbRRVGWHtMd-Ixl8a7DEBxsAGpZ2VJwQ
Content-Type: application/json

{
    "name": "Toan Do"
}

###

GET http://localhost:3000/person/get-list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NjY5NDM2NTcsInV1aWQiOjkzNjIsInVzZXJuYW1lIjoiQzIwMjExMDE1ODg4OCJ9.ax0L91BP0vXMzWISu8tntIiXUr5ts1b_1Tk_YZJmuYt9ikQ9gl8TCwwbRRVGWHtMd-Ixl8a7DEBxsAGpZ2VJwQ